# Generated by Django 3.1.6 on 2022-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=10, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('company', models.CharField(max_length=50)),
                ('emp_id', models.IntegerField()),
                ('manager', models.CharField(max_length=50)),
            ],
        ),
    ]
