# Generated by Django 3.1.6 on 2022-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='file',
            field=models.FileField(default='No File found', upload_to=''),
        ),
    ]
